all:
  hosts:
    01-k8s-cp:
      ansible_host: 172.30.0.10
      ip: 172.30.0.10
      access_ip: 172.30.0.10
    01-k8s-worker01:
      ansible_host: 172.30.0.11
      ip: 172.30.0.11
      access_ip: 172.30.0.11
    01-k8s-worker02:
      ansible_host: 172.30.0.12
      ip: 172.30.0.12
      access_ip: 172.30.0.12
  children:
    kube_control_plane:
      hosts:
        01-k8s-cp:
    kube_node:
      hosts:
        01-k8s-worker01:
        01-k8s-worker02:
    etcd:
      hosts:
        01-k8s-cp:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
